### ISSUE TITLE
Default to development in docker

### ISSUE THREAD

**Issue by bcaldwell** [bcaldwell/devctl#63]
I think it make sense to default to running code in a docker container unless the user manual overrides it. This makes it a lot easier to manages dependencies as well.

I propose adding a docker bool options to devclt.yml to disable this
```
---
go:
  version: 6

docker: true
docker_options:
  image: golang
  tag: 1.7
  src_directory: /go/src/github.com/...
  
scripts:
  hello:
    desc: blah
    command: echo hello
    docker: false
```

@karanthukral
